version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/node-aws-local-dev

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
      timeout: 30

  ApplicationStart:
    - location: scripts/run.sh
      runas: root
      timeout: 30
