version: 0.2

env:
  parameter-store:
    MY_TEST: NODE_AWS_TEST      

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  build:
    commands:
      - echo ${MY_TEST} 
      - echo $CODEBUILD_BUILD_NUMBER 
      - npm run build
      - npm run test
      - npm run test:e2e
  post_build:
    commands:
      - mkdir release
      - cp -R node_modules/ release
      - cp -R dist/ release
      - zip -qr release.zip release      

artifacts:
  files:
    - release.zip
    