version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  build:
    commands:
      - echo $CODEBUILD_BUILD_NUMBER 
      - npm run build
      - npm run test
      - npm run test:e2e
  post_build:
    commands:
      - mkdir release
      - cp -R node_modules/ release
      - cp -R dist/ release
      - zip -qr release${CODEBUILD_BUILD_NUMBER}.zip release      

artifacts:
  files:
    - release${CODEBUILD_BUILD_NUMBER}.zip
    