version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  build:
    commands:
      - npm run build
      - npm run test
      - npm run test:e2e

artifacts:
  type: zip
  files:
    - dist
    - node_modules
